version: '3.3'
services:
  db:
    container_name: db
    image: mysql
    # ports:
    #   - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
  adminer:
    container_name: db_adminer
    image: adminer
    restart: always
    ports:
      - 8000:8080
  demo_app:
    container_name: demo_app
    build: .
    volumes:
      - ./:/usr/src/
      - /usr/src/node_modules
      - /usr/src/dist
    ports:
      - 3000:3000
    extra_hosts:
      - localhost:127.0.0.1
    env_file:
      - .env
    depends_on:
      - db
  redis:
    image: redis
    container_name: redis
    restart: always
    # ports:
    #   - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
